CIRCUITPY_PYSTACK_SIZE=4096 ### 4096 tested as good on Metro M4. ###
CIRCUITPY_WIFI_SSID=### YOUR SSID HERE ###
CIRCUITPY_WIFI_PASSWORD=### YOUR WIFI PW HERE ###
NETCONFIG_URL=### NETCONFIG URL. NOT YET IMPLEMENTED ###